/**
 * DisclosurePublisherAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisclosurePublisherAdapter
 *
 * DDD: Infrastructure adapter that implements DisclosurePublisher port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DisclosurePublisher,
} from "@aliaskeep/services/classification";
import type { HttpClient } from "../_shared/http-client.js";
import { sandbox } from "../_shared/sandbox-repo.js";


/**
 * DisclosurePublisherAdapter
 *
 * Implements DisclosurePublisher port for infrastructure layer.
 */
export class DisclosurePublisherAdapter implements DisclosurePublisher {
  constructor(
    private readonly http: HttpClient
  ) {}

  async publishUploadDisclosure(input: Parameters<DisclosurePublisher['publishUploadDisclosure']>[0]): Promise<Awaited<ReturnType<DisclosurePublisher['publishUploadDisclosure']>>> {
    return sandbox('publishUploadDisclosure', input) as Awaited<ReturnType<DisclosurePublisher['publishUploadDisclosure']>>;
  }
}
