/**
 * QuarantineRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QuarantineRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements QuarantineRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  QuarantineRepository,
} from "@aliaskeep/services/classification";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { QuarantineRepositoryDdb } from "./quarantine-repository.ddb.js";

/**
 * QuarantineRepositoryAdapter
 *
 * Implements QuarantineRepository port for infrastructure layer.
 */
export class QuarantineRepositoryAdapter implements QuarantineRepository {
  private readonly ddb: QuarantineRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new QuarantineRepositoryDdb(this.dynamoClient);
  }

  async listQuarantineItems(input: Parameters<QuarantineRepository['listQuarantineItems']>[0]): Promise<Awaited<ReturnType<QuarantineRepository['listQuarantineItems']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listQuarantineItems(input);
  }

  async getQuarantineItem(input: Parameters<QuarantineRepository['getQuarantineItem']>[0]): Promise<Awaited<ReturnType<QuarantineRepository['getQuarantineItem']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getQuarantineItem(input);
  }
}
