/**
 * ExecuteSubmitClassificationScan - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSubmitClassificationScan Use Case
 *
 * DDD: Application use case for create Scan.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SubmitClassificationScanInput, SubmitClassificationScanOutput } from "../dto/scan.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { ScanRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteSubmitClassificationScan {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scan: ScanRepository
  ) {}

  async execute(input: SubmitClassificationScanInput): Promise<SubmitClassificationScanOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.clsId();

    // All field names extracted from OpenAPI spec: channelId, contentBase64, fieldPath, payloadType, proposalRef
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.payloadType) {
      throw new ValidationError("payloadType is required");
    }
    if (!input.proposalRef) {
      throw new ValidationError("proposalRef is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (classification domain)
    const entityId = this.idGenerator.clsId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.scan.submitClassificationScan({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as SubmitClassificationScanOutput;
  }
}
