/**
 * ExecutePublishUploadDisclosure - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePublishUploadDisclosure Use Case
 *
 * DDD: Application use case for get Disclosure.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PublishUploadDisclosureInput, PublishUploadDisclosureOutput } from "../dto/disclosure.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { DisclosurePublisher, DisclosureRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecutePublishUploadDisclosure {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly disclosureRepository: DisclosureRepository,
    private readonly disclosurePublisher: DisclosurePublisher
  ) {}

  async execute(input: PublishUploadDisclosureInput): Promise<PublishUploadDisclosureOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.clsId();

    // All field names extracted from OpenAPI spec: fields, requireAdapterAck, version
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.disclosurePublisher.publishUploadDisclosure({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as PublishUploadDisclosureOutput;
  }
}
