/**
 * ErasureRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ErasureRepository Port
 *
 * DDD: Application port for erasurerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExecuteLogicalErasureInput, ExecuteLogicalErasureOutput, GetLogicalErasureInput, GetLogicalErasureOutput, ListLogicalErasuresInput, ListLogicalErasuresOutput } from "../dto/erasure.dto";
export interface ErasureRepository {
  listLogicalErasures(input: ListLogicalErasuresInput): Promise<ListLogicalErasuresOutput>;
  executeLogicalErasure(input: ExecuteLogicalErasureInput): Promise<ExecuteLogicalErasureOutput>;
  getLogicalErasure(input: GetLogicalErasureInput): Promise<GetLogicalErasureOutput>;
}

export type { ExecuteLogicalErasureInput, ExecuteLogicalErasureOutput, GetLogicalErasureInput, GetLogicalErasureOutput, ListLogicalErasuresInput, ListLogicalErasuresOutput } from "../dto/erasure.dto";
