/**
 * Routes for Reject
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { rejectQuarantineItem } from "../handlers/reject.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function rejectRoutes(fastify: FastifyInstance) {
  // POST /v1/classification/quarantine/{quarantineId}/reject (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/classification/quarantine/:quarantineId/reject",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { quarantineId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getClassificationDependenciesForRequest();
        await rejectQuarantineItem(request, reply, deps);
      });
    }
  );


}
