/**
 * Quarantine DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Quarantine DTOs
 *
 * DDD: Application DTOs for Quarantine use cases.
 */

import type { GetQuarantineItemParams, ListQuarantineItemsParams } from "@aliaskeep/core/classification/types";

export type ListQuarantineItemsInput = ListQuarantineItemsParams;

export type GetQuarantineItemInput = GetQuarantineItemParams;

export type ListQuarantineItemsOutput = {};

export type GetQuarantineItemOutput = {};
