/**
 * Scan DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Scan DTOs
 *
 * DDD: Application DTOs for Scan use cases.
 */

import type { SubmitClassificationScanRequestInput } from "@aliaskeep/core/classification/types";

export type SubmitClassificationScanInput = SubmitClassificationScanRequestInput;

export type SubmitClassificationScanOutput = {};
