/**
 * Waive DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Waive DTOs
 *
 * DDD: Application DTOs for Waive use cases.
 */

import type { WaiveQuarantineItemParams, WaiveQuarantineItemRequestInput } from "@aliaskeep/core/classification/types";

export type WaiveQuarantineItemInput = WaiveQuarantineItemParams & WaiveQuarantineItemRequestInput;

export type WaiveQuarantineItemOutput = {};
