/**
 * GetLinkAudit DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetLinkAuditReportParams } from "@aliaskeep/core/reporting";

export function createGetLinkAuditRequest(overrides: Partial<GetLinkAuditReportParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
