/**
 * Profile DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fabric
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Profile DTOs
 *
 * DDD: Application DTOs for Profile use cases.
 */

import type { GetFabricIdentityProfileParams, ListFabricIdentityProfilesParams, SubmitFabricEnrollmentScanRequestInput } from "@aliaskeep/core/fabric/types";

export type ListFabricIdentityProfilesInput = ListFabricIdentityProfilesParams;

export type SubmitFabricEnrollmentScanInput = SubmitFabricEnrollmentScanRequestInput;

export type GetFabricIdentityProfileInput = GetFabricIdentityProfileParams;

export type ListFabricIdentityProfilesOutput = {};

export type SubmitFabricEnrollmentScanOutput = {};

export type GetFabricIdentityProfileOutput = {};
