/**
 * RequirePath DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fabric
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RequirePath DTOs
 *
 * DDD: Application DTOs for RequirePath use cases.
 */

import type { RequireFabricIdentityPathParams, RequireFabricIdentityPathRequestInput } from "@aliaskeep/core/fabric/types";

export type RequireFabricIdentityPathInput = RequireFabricIdentityPathParams & RequireFabricIdentityPathRequestInput;

export type RequireFabricIdentityPathOutput = {};
