/**
 * FlagDuplicateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FlagDuplicateRepository Port
 *
 * DDD: Application port for flagduplicaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { FlagVaultDuplicateInput, FlagVaultDuplicateOutput } from "../dto/flag-duplicate.dto";
export interface FlagDuplicateRepository {
  flagVaultDuplicate(input: FlagVaultDuplicateInput): Promise<FlagVaultDuplicateOutput>;
}

export type { FlagVaultDuplicateInput, FlagVaultDuplicateOutput } from "../dto/flag-duplicate.dto";
