/**
 * VaultRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VaultRepository Port
 *
 * DDD: Application port for vaultrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateIdentityVaultInput, CreateIdentityVaultOutput, GetIdentityVaultInput, GetIdentityVaultOutput, ListIdentityVaultsInput, ListIdentityVaultsOutput } from "../dto/vault.dto";
export interface VaultRepository {
  listIdentityVaults(input: ListIdentityVaultsInput): Promise<ListIdentityVaultsOutput>;
  createIdentityVault(input: CreateIdentityVaultInput): Promise<CreateIdentityVaultOutput>;
  getIdentityVault(input: GetIdentityVaultInput): Promise<GetIdentityVaultOutput>;
}

export type { CreateIdentityVaultInput, CreateIdentityVaultOutput, GetIdentityVaultInput, GetIdentityVaultOutput, ListIdentityVaultsInput, ListIdentityVaultsOutput } from "../dto/vault.dto";
