/**
 * ExecuteListLinkGrants - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListLinkGrants Use Case
 *
 * DDD: Application use case for list Grant.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListLinkGrantsInput, ListLinkGrantsOutput } from "../dto/grant.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { GrantRepository } from "../ports";

export class ExecuteListLinkGrants {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly grant: GrantRepository
  ) {}

  async execute(input: ListLinkGrantsInput): Promise<ListLinkGrantsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lnkId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.grant.listLinkGrants({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListLinkGrantsOutput;
  }
}
