/**
 * ExecuteRevokeLinkGrant - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRevokeLinkGrant Use Case
 *
 * DDD: Application use case for get Revoke.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RevokeLinkGrantInput, RevokeLinkGrantOutput } from "../dto/revoke.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { RevokeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRevokeLinkGrant {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly revoke: RevokeRepository
  ) {}

  async execute(input: RevokeLinkGrantInput): Promise<RevokeLinkGrantOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lnkId();

    // All field names extracted from OpenAPI spec: reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).grantId) {
      throw new ValidationError("grantId is required");
    }
    const grantId = (input as any).grantId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.revoke.revokeLinkGrant({ grantId: grantId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${grantId}`);
    }

    return entity as RevokeLinkGrantOutput;
  }
}
