/**
 * ExecuteSuspendLinkGrant - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSuspendLinkGrant Use Case
 *
 * DDD: Application use case for get Suspend.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SuspendLinkGrantInput, SuspendLinkGrantOutput } from "../dto/suspend.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { SuspendRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteSuspendLinkGrant {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly suspend: SuspendRepository
  ) {}

  async execute(input: SuspendLinkGrantInput): Promise<SuspendLinkGrantOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lnkId();

    // All field names extracted from OpenAPI spec: note, reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).grantId) {
      throw new ValidationError("grantId is required");
    }
    const grantId = (input as any).grantId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.suspend.suspendLinkGrant({ grantId: grantId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${grantId}`);
    }

    return entity as SuspendLinkGrantOutput;
  }
}
