/**
 * ExecuteExecuteLogicalErasure - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExecuteLogicalErasure Use Case
 *
 * DDD: Application use case for create Erasure.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExecuteLogicalErasureInput, ExecuteLogicalErasureOutput } from "../dto/erasure.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { ErasureRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteExecuteLogicalErasure {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly erasure: ErasureRepository
  ) {}

  async execute(input: ExecuteLogicalErasureInput): Promise<ExecuteLogicalErasureOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ersId();

    // All field names extracted from OpenAPI spec: erasureReason, notifyParticipants, vaultId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.vaultId) {
      throw new ValidationError("vaultId is required");
    }
    if (!input.erasureReason) {
      throw new ValidationError("erasureReason is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (erasures domain)
    const entityId = this.idGenerator.ersId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.erasure.executeLogicalErasure({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as ExecuteLogicalErasureOutput;
  }
}
