/**
 * Handlers for Propagation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ErasuresDomainModule } from "../dependencies/erasures-ddd.dependencies.js";
import type { GetErasurePropagationInput } from "@aliaskeep/services/erasures";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/erasures/{erasureId}/propagation
 * Operation: getErasurePropagation
 */
export async function getErasurePropagation(
  request: FastifyRequest<{ Params: { erasureId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ErasuresDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetErasurePropagationInput = {
    erasureId: request.params.erasureId,
  };
  const result = await deps.useCases.propagations.get.execute(input);
  return reply.code(200).send(result);
}


