/**
 * ExportJobRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportJobRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExportJobRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExportJobRepository,
} from "@aliaskeep/services/reporting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { JobRepositoryDdb } from "./job-repository.ddb.js";

/**
 * ExportJobRepositoryAdapter
 *
 * Implements ExportJobRepository port for infrastructure layer.
 */
export class ExportJobRepositoryAdapter implements ExportJobRepository {
  private readonly ddb: JobRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new JobRepositoryDdb(this.dynamoClient);
  }

  async listReportExportJobs(input: Parameters<ExportJobRepository['listReportExportJobs']>[0]): Promise<Awaited<ReturnType<ExportJobRepository['listReportExportJobs']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listReportExportJobs(input);
  }

  async createReportExportJob(input: Parameters<ExportJobRepository['createReportExportJob']>[0]): Promise<Awaited<ReturnType<ExportJobRepository['createReportExportJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createReportExportJob(input);
  }

  async getReportExportJob(input: Parameters<ExportJobRepository['getReportExportJob']>[0]): Promise<Awaited<ReturnType<ExportJobRepository['getReportExportJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getReportExportJob(input);
  }
}
