/**
 * HomeSummaryRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HomeSummaryRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements HomeSummaryRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  HomeSummaryRepository,
} from "@aliaskeep/services/reporting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { HomeSummaryRepositoryDdb } from "./home-summary-repository.ddb.js";

/**
 * HomeSummaryRepositoryAdapter
 *
 * Implements HomeSummaryRepository port for infrastructure layer.
 */
export class HomeSummaryRepositoryAdapter implements HomeSummaryRepository {
  private readonly ddb: HomeSummaryRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new HomeSummaryRepositoryDdb(this.dynamoClient);
  }

  async getArchitectHomeSummary(input: Parameters<HomeSummaryRepository['getArchitectHomeSummary']>[0]): Promise<Awaited<ReturnType<HomeSummaryRepository['getArchitectHomeSummary']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getArchitectHomeSummary(input);
  }
}
