/**
 * ExecuteListIdentityVaults - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListIdentityVaults Use Case
 *
 * DDD: Application use case for list Vault.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListIdentityVaultsInput, ListIdentityVaultsOutput } from "../dto/vault.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { VaultRepository } from "../ports";

export class ExecuteListIdentityVaults {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly vault: VaultRepository
  ) {}

  async execute(input: ListIdentityVaultsInput): Promise<ListIdentityVaultsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vltId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.vault.listIdentityVaults({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListIdentityVaultsOutput;
  }
}
