/**
 * ErasureCertificate Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/erasures.openapi.types.js";
import { schemas } from "../schemas/erasures.schemas.js";

/**
 * Entity: ErasureCertificateEntity
 * Description: Represents the ErasureCertificate domain model.
 * Source: schemas.ErasureCertificate
 * Type: Domain Entity (API)
 */
export const ErasureCertificateEntitySchema = schemas.ErasureCertificate;
export type ErasureCertificateEntity = components["schemas"]["ErasureCertificate"];
