/**
 * GetVault DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetIdentityVaultParams } from "@aliaskeep/core/vaults";

export function createGetVaultRequest(overrides: Partial<GetIdentityVaultParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
