/**
 * Handlers for Disclosure
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ClassificationDomainModule } from "../dependencies/classification-ddd.dependencies.js";
import type { GetUploadDisclosureInput, PublishUploadDisclosureInput } from "@aliaskeep/services/classification";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/classification/disclosure
 * Operation: getUploadDisclosure
 */
export async function getUploadDisclosure(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ClassificationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetUploadDisclosureInput = {};
  const result = await deps.useCases.disclosures.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/classification/disclosure
 * Operation: publishUploadDisclosure
 */
export async function publishUploadDisclosure(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ClassificationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PublishUploadDisclosureInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.disclosures.get.execute(input);
  return reply.code(200).send(result);
}


