/**
 * Handlers for Reject
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ClassificationDomainModule } from "../dependencies/classification-ddd.dependencies.js";
import type { RejectQuarantineItemInput } from "@aliaskeep/services/classification";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/classification/quarantine/{quarantineId}/reject
 * Operation: rejectQuarantineItem
 */
export async function rejectQuarantineItem(
  request: FastifyRequest<{ Params: { quarantineId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ClassificationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RejectQuarantineItemInput = {
    quarantineId: request.params.quarantineId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.rejects.create.execute(input);
  return reply.code(200).send(result);
}


