/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @aliaskeep/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@aliaskeep/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@aliaskeep/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@aliaskeep/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@aliaskeep/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@aliaskeep/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _classification from "./classification/index.js";
import * as _erasures from "./erasures/index.js";
import * as _fabric from "./fabric/index.js";
import * as _identity from "./identity/index.js";
import * as _links from "./links/index.js";
import * as _participants from "./participants/index.js";
import * as _reporting from "./reporting/index.js";
import * as _vaults from "./vaults/index.js";

// Export as namespaces
export const _shared = __shared;
export const classification = _classification;
export const erasures = _erasures;
export const fabric = _fabric;
export const identity = _identity;
export const links = _links;
export const participants = _participants;
export const reporting = _reporting;
export const vaults = _vaults;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@aliaskeep/core"; activity.types.*
//   - Direct exports: import * from "@aliaskeep/core/activity/types/index.js"
//   - Direct exports: import * from "@aliaskeep/core/activity/repositories/index.js"
//   - Direct exports: import * from "@aliaskeep/core/activity/models/index.js"
//   - Direct exports: import * from "@aliaskeep/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Classification Service
export { schemas as ClassificationSchemas } from "./classification/schemas/classification.schemas.js";

// Erasures Service
export { schemas as ErasuresSchemas } from "./erasures/schemas/erasures.schemas.js";

// Fabric Service
export { schemas as FabricSchemas } from "./fabric/schemas/fabric.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Links Service
export { schemas as LinksSchemas } from "./links/schemas/links.schemas.js";

// Participants Service
export { schemas as ParticipantsSchemas } from "./participants/schemas/participants.schemas.js";

// Reporting Service
export { schemas as ReportingSchemas } from "./reporting/schemas/reporting.schemas.js";

// Vaults Service
export { schemas as VaultsSchemas } from "./vaults/schemas/vaults.schemas.js";

