/**
 * RequirePathRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fabric
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RequirePathRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RequirePathRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RequirePathRepository,
} from "@aliaskeep/services/fabric";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RequirePathRepositoryDdb } from "./require-path-repository.ddb.js";

/**
 * RequirePathRepositoryAdapter
 *
 * Implements RequirePathRepository port for infrastructure layer.
 */
export class RequirePathRepositoryAdapter implements RequirePathRepository {
  private readonly ddb: RequirePathRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RequirePathRepositoryDdb(this.dynamoClient);
  }

  async requireFabricIdentityPath(input: Parameters<RequirePathRepository['requireFabricIdentityPath']>[0]): Promise<Awaited<ReturnType<RequirePathRepository['requireFabricIdentityPath']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requireFabricIdentityPath(input);
  }
}
