/**
 * LinkAudit DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LinkAudit DTOs
 *
 * DDD: Application DTOs for LinkAudit use cases.
 */

import type { GetLinkAuditReportParams } from "@aliaskeep/core/reporting/types";

export type GetLinkAuditReportInput = GetLinkAuditReportParams;

export type GetLinkAuditReportOutput = {};
