/**
 * ExecuteRevokeParticipant - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRevokeParticipant Use Case
 *
 * DDD: Application use case for get Revoke.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RevokeParticipantInput, RevokeParticipantOutput } from "../dto/revoke.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { RevokeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRevokeParticipant {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly revoke: RevokeRepository
  ) {}

  async execute(input: RevokeParticipantInput): Promise<RevokeParticipantOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prtId();

    // All field names extracted from OpenAPI spec: reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).participantId) {
      throw new ValidationError("participantId is required");
    }
    const participantId = (input as any).participantId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.revoke.revokeParticipant({ participantId: participantId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${participantId}`);
    }

    return entity as RevokeParticipantOutput;
  }
}
