/**
 * ExecuteAttestParticipant - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAttestParticipant Use Case
 *
 * DDD: Application use case for get Attest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AttestParticipantInput, AttestParticipantOutput } from "../dto/attest.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { AttestRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAttestParticipant {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly attest: AttestRepository
  ) {}

  async execute(input: AttestParticipantInput): Promise<AttestParticipantOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prtId();

    // All field names extracted from OpenAPI spec: channelIds, gdprRole, jurisdiction
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).participantId) {
      throw new ValidationError("participantId is required");
    }
    const participantId = (input as any).participantId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.attest.attestParticipant({ participantId: participantId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${participantId}`);
    }

    return entity as AttestParticipantOutput;
  }
}
