/**
 * ExportJobRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportJobRepository Port
 *
 * DDD: Application port for exportjobrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateReportExportJobInput, CreateReportExportJobOutput, GetReportExportJobInput, GetReportExportJobOutput, ListReportExportJobsInput, ListReportExportJobsOutput } from "../dto/export-job.dto";
export interface ExportJobRepository {
  listReportExportJobs(input: ListReportExportJobsInput): Promise<ListReportExportJobsOutput>;
  createReportExportJob(input: CreateReportExportJobInput): Promise<CreateReportExportJobOutput>;
  getReportExportJob(input: GetReportExportJobInput): Promise<GetReportExportJobOutput>;
}

export type { CreateReportExportJobInput, CreateReportExportJobOutput, GetReportExportJobInput, GetReportExportJobOutput, ListReportExportJobsInput, ListReportExportJobsOutput } from "../dto/export-job.dto";
