/**
 * HomeSummaryRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HomeSummaryRepository Port
 *
 * DDD: Application port for homesummaryrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetArchitectHomeSummaryInput, GetArchitectHomeSummaryOutput } from "../dto/home-summary.dto";
export interface HomeSummaryRepository {
  getArchitectHomeSummary(input: GetArchitectHomeSummaryInput): Promise<GetArchitectHomeSummaryOutput>;
}

export type { GetArchitectHomeSummaryInput, GetArchitectHomeSummaryOutput } from "../dto/home-summary.dto";
