/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { policyRoutes } from "./policy.routes.js";
export { approveRoutes } from "./approve.routes.js";
export { grantRoutes } from "./grant.routes.js";
export { rejectRoutes } from "./reject.routes.js";
export { restoreRoutes } from "./restore.routes.js";
export { revokeRoutes } from "./revoke.routes.js";
export { suspendRoutes } from "./suspend.routes.js";
