/**
 * Routes for Suspend
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { suspendLinkGrant } from "../handlers/suspend.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function suspendRoutes(fastify: FastifyInstance) {
  // POST /v1/links/grants/{grantId}/suspend (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/links/grants/:grantId/suspend",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { grantId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLinksDependenciesForRequest();
        await suspendLinkGrant(request, reply, deps);
      });
    }
  );


}
