/**
 * ExecuteListReportExportJobs - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListReportExportJobs Use Case
 *
 * DDD: Application use case for list ExportJob.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListReportExportJobsInput, ListReportExportJobsOutput } from "../dto/export-job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { ExportJobRepository } from "../ports";

export class ExecuteListReportExportJobs {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportJob: ExportJobRepository
  ) {}

  async execute(input: ListReportExportJobsInput): Promise<ListReportExportJobsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.exportJob.listReportExportJobs({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListReportExportJobsOutput;
  }
}
