/**
 * ExecuteGetReportExportJob - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetReportExportJob Use Case
 *
 * DDD: Application use case for get ExportJob.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetReportExportJobInput, GetReportExportJobOutput } from "../dto/export-job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { ExportJobRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetReportExportJob {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportJob: ExportJobRepository
  ) {}

  async execute(input: GetReportExportJobInput): Promise<GetReportExportJobOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).jobId) {
      throw new ValidationError("jobId is required");
    }
    const jobId = (input as any).jobId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.exportJob.getReportExportJob({ jobId: jobId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${jobId}`);
    }

    return entity as GetReportExportJobOutput;
  }
}
