/**
 * Routes for ExportJob
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createReportExportJob, getReportExportJob, listReportExportJobs } from "../handlers/export-job.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function exportJobRoutes(fastify: FastifyInstance) {
  // POST /v1/reports/export-jobs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/reports/export-jobs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getReportingDependenciesForRequest();
        await createReportExportJob(request, reply, deps);
      });
    }
  );


  // GET /v1/reports/export-jobs (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/reports/export-jobs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getReportingDependenciesForRequest();
        await listReportExportJobs(request, reply, deps);
      });
    }
  );


  // GET /v1/reports/export-jobs/{jobId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/reports/export-jobs/:jobId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getReportingDependenciesForRequest();
        await getReportExportJob(request, reply, deps);
      });
    }
  );


}
