/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { homeSummaryRoutes } from "./home-summary.routes.js";
export { linkAuditRoutes } from "./link-audit.routes.js";
export { exportJobRoutes } from "./export-job.routes.js";
