/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fabric
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Fabric Domain Use Cases
 * 
 * List of all use case names for the fabric domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const FABRIC_USE_CASES = [
  "executeGetFabricIdentityProfile",
  "executeListFabricIdentityProfiles",
  "executeRequireFabricIdentityPath",
  "executeSubmitFabricEnrollmentScan"
] as const;
