/**
 * Reporting DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reporting Domain Module - Composition root
 *
 * DDD: Composition root for reporting domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  HomeSummaryRepositoryAdapter,
  LinkAuditRepositoryAdapter,
} from "@aliaskeep/adapters/reporting";
import { getIdGeneratorService } from "@aliaskeep/adapters";
import type { AdapterDynamoDBClient } from "@aliaskeep/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateReportExportJob,
  ExecuteGetArchitectHomeSummary,
  ExecuteGetLinkAuditReport,
  ExecuteGetReportExportJob,
  ExecuteListReportExportJobs,
} from "@aliaskeep/services/reporting/usecases";
// Ports (interfaces)
import type {
  HomeSummaryRepository,
  LinkAuditRepository,
} from "@aliaskeep/services/reporting/ports";

export interface ReportingDomainModule {
  repos: {
    homeSummaries: HomeSummaryRepository;
    linkAudits: LinkAuditRepository;
  };
  useCases: {
    homeSummaries: {
      get: ExecuteGetArchitectHomeSummary;
    };
    linkAudits: {
      get: ExecuteGetLinkAuditReport;
    };
  };
}

export function buildReportingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReportingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      homeSummaries?: HomeSummaryRepository;
      linkAudits?: LinkAuditRepository;
    } = {};

    obj.homeSummaries = new HomeSummaryRepositoryAdapter(dynamoClient);
    obj.linkAudits = new LinkAuditRepositoryAdapter(dynamoClient);
    return {
      homeSummaries: obj.homeSummaries!,
      linkAudits: obj.linkAudits!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    homeSummaries: {
      get: new ExecuteGetArchitectHomeSummary(executionContext, idGenerator, repos.homeSummaries),
    },
    linkAudits: {
      get: new ExecuteGetLinkAuditReport(executionContext, idGenerator, repos.linkAudits),
    },
  };
  return { repos, useCases: useCases as ReportingDomainModule["useCases"] };
}
