/**
 * ExecuteListFabricIdentityProfiles - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fabric
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFabricIdentityProfiles Use Case
 *
 * DDD: Application use case for list Profile.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFabricIdentityProfilesInput, ListFabricIdentityProfilesOutput } from "../dto/profile.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aliaskeep/services/_shared/index.js";
import type { ProfileRepository } from "../ports";

export class ExecuteListFabricIdentityProfiles {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly profile: ProfileRepository
  ) {}

  async execute(input: ListFabricIdentityProfilesInput): Promise<ListFabricIdentityProfilesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fabId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.profile.listFabricIdentityProfiles({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFabricIdentityProfilesOutput;
  }
}
