/**
 * Handlers for Grant
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LinksDomainModule } from "../dependencies/links-ddd.dependencies.js";
import type { AllocateLinkGrantInput, GetLinkGrantInput, ListLinkGrantsInput } from "@aliaskeep/services/links";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/links/grants
 * Operation: listLinkGrants
 */
export async function listLinkGrants(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], vaultId?: string | string[], pseudonymId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: LinksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListLinkGrantsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.grants.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/links/grants
 * Operation: allocateLinkGrant
 */
export async function allocateLinkGrant(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: LinksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AllocateLinkGrantInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.grants.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/links/grants/{grantId}
 * Operation: getLinkGrant
 */
export async function getLinkGrant(
  request: FastifyRequest<{ Params: { grantId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: LinksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetLinkGrantInput = {
    grantId: request.params.grantId,
  };
  const result = await deps.useCases.grants.get.execute(input);
  return reply.code(200).send(result);
}


