/**
 * GetFabricIdentityProfile handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fabric
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getFabricIdentityProfile } from "@aliaskeep/api-server/domains/fabric/handlers";
import type { FabricDDDDependencies } from "@aliaskeep/api-server/domains/fabric";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aliaskeep/tests/shared";
import { FABRIC_USE_CASES } from "../__factories__/use-cases.js";

describe("GetFabricIdentityProfile", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FabricDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FabricDDDDependencies>(
      FABRIC_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetFabricIdentityProfile, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { profileId: entity.id };

    await getFabricIdentityProfile(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetFabricIdentityProfile.execute).toHaveBeenCalledWith(expect.objectContaining({ profileId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { profileId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetFabricIdentityProfile, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getFabricIdentityProfile(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
