/**
 * ListFabricIdentityProfiles handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fabric
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listFabricIdentityProfiles } from "@aliaskeep/api-server/domains/fabric/handlers";
import type { FabricDDDDependencies } from "@aliaskeep/api-server/domains/fabric";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aliaskeep/tests/shared";
import { FABRIC_USE_CASES } from "../__factories__/use-cases.js";

describe("ListFabricIdentityProfiles", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FabricDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FabricDDDDependencies>(
      FABRIC_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      { id: 'mock-1', orgId } as any,
      { id: 'mock-2', orgId } as any,
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListFabricIdentityProfiles, "execute").mockResolvedValue(useCaseResult);

    await listFabricIdentityProfiles(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListFabricIdentityProfiles.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
