/**
 * Routes for Attest
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { attestParticipant } from "../handlers/attest.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function attestRoutes(fastify: FastifyInstance) {
  // POST /v1/participants/{participantId}/attest (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/participants/:participantId/attest",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { participantId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getParticipantsDependenciesForRequest();
        await attestParticipant(request, reply, deps);
      });
    }
  );


}
