/**
 * GetGrant DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetLinkGrantParams } from "@aliaskeep/core/links";

export function createGetGrantRequest(overrides: Partial<GetLinkGrantParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
