/**
 * GrantRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GrantRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GrantRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GrantRepository,
} from "@aliaskeep/services/links";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GrantRepositoryDdb } from "./grant-repository.ddb.js";

/**
 * GrantRepositoryAdapter
 *
 * Implements GrantRepository port for infrastructure layer.
 */
export class GrantRepositoryAdapter implements GrantRepository {
  private readonly ddb: GrantRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GrantRepositoryDdb(this.dynamoClient);
  }

  async listLinkGrants(input: Parameters<GrantRepository['listLinkGrants']>[0]): Promise<Awaited<ReturnType<GrantRepository['listLinkGrants']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listLinkGrants(input);
  }

  async allocateLinkGrant(input: Parameters<GrantRepository['allocateLinkGrant']>[0]): Promise<Awaited<ReturnType<GrantRepository['allocateLinkGrant']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.allocateLinkGrant(input);
  }

  async getLinkGrant(input: Parameters<GrantRepository['getLinkGrant']>[0]): Promise<Awaited<ReturnType<GrantRepository['getLinkGrant']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLinkGrant(input);
  }
}
