/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve-repository.ddb.js";
export * from "./grant-repository.ddb.js";
export * from "./policy-repository.ddb.js";
export * from "./reject-repository.ddb.js";
export * from "./restore-repository.ddb.js";
export * from "./revoke-repository.ddb.js";
export * from "./suspend-repository.ddb.js";
export * from "./approve-repository.adapter.js";
export * from "./grant-repository.adapter.js";
export * from "./policy-repository.adapter.js";
export * from "./reject-repository.adapter.js";
export * from "./restore-repository.adapter.js";
export * from "./revoke-repository.adapter.js";
export * from "./suspend-repository.adapter.js";
