/**
 * GetLinkGrant handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getLinkGrant } from "@aliaskeep/api-server/domains/links/handlers";
import type { LinksDDDDependencies } from "@aliaskeep/api-server/domains/links";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aliaskeep/tests/shared";
import { LINKS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetLinkGrant", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: LinksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<LinksDDDDependencies>(
      LINKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetLinkGrant, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { grantId: entity.id };

    await getLinkGrant(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetLinkGrant.execute).toHaveBeenCalledWith(expect.objectContaining({ grantId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { grantId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetLinkGrant, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getLinkGrant(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
