/**
 * Fabric DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fabric
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Fabric Domain Module - Composition root
 *
 * DDD: Composition root for fabric domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ProfileRepositoryAdapter,
  RequirePathRepositoryAdapter,
} from "@aliaskeep/adapters/fabric";
import { getIdGeneratorService } from "@aliaskeep/adapters";
import type { AdapterDynamoDBClient } from "@aliaskeep/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetFabricIdentityProfile,
  ExecuteListFabricIdentityProfiles,
  ExecuteRequireFabricIdentityPath,
  ExecuteSubmitFabricEnrollmentScan,
} from "@aliaskeep/services/fabric/usecases";
// Ports (interfaces)
import type {
  ProfileRepository,
  RequirePathRepository,
} from "@aliaskeep/services/fabric/ports";

export interface FabricDomainModule {
  repos: {
    profiles: ProfileRepository;
    requirePaths: RequirePathRepository;
  };
  useCases: {
    profiles: {
      create: ExecuteSubmitFabricEnrollmentScan;
      get: ExecuteGetFabricIdentityProfile;
      list: ExecuteListFabricIdentityProfiles;
    };
    requirePaths: {
      get: ExecuteRequireFabricIdentityPath;
    };
  };
}

export function buildFabricDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): FabricDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      profiles?: ProfileRepository;
      requirePaths?: RequirePathRepository;
    } = {};

    obj.profiles = new ProfileRepositoryAdapter(dynamoClient);
    obj.requirePaths = new RequirePathRepositoryAdapter(dynamoClient);
    return {
      profiles: obj.profiles!,
      requirePaths: obj.requirePaths!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    profiles: {
      create: new ExecuteSubmitFabricEnrollmentScan(executionContext, idGenerator, repos.profiles),
      get: new ExecuteGetFabricIdentityProfile(executionContext, idGenerator, repos.profiles),
      list: new ExecuteListFabricIdentityProfiles(executionContext, idGenerator, repos.profiles),
    },
    requirePaths: {
      get: new ExecuteRequireFabricIdentityPath(executionContext, idGenerator, repos.requirePaths),
    },
  };
  return { repos, useCases: useCases as FabricDomainModule["useCases"] };
}
