/**
 * ErasureCertificate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ErasureCertificate DTOs
 *
 * DDD: Application DTOs for ErasureCertificate use cases.
 */

import type { GetErasureCertificateParams } from "@aliaskeep/core/erasures/types";

export type GetErasureCertificateInput = GetErasureCertificateParams;

export type GetErasureCertificateOutput = {};
