/**
 * Nudge DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Nudge DTOs
 *
 * DDD: Application DTOs for Nudge use cases.
 */

import type { NudgeErasurePropagationParams, NudgeErasurePropagationRequestInput } from "@aliaskeep/core/erasures/types";

export type NudgeErasurePropagationInput = NudgeErasurePropagationParams & NudgeErasurePropagationRequestInput;

export type NudgeErasurePropagationOutput = {};
