/**
 * GetQuarantineItem handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getQuarantineItem } from "@aliaskeep/api-server/domains/classification/handlers";
import type { ClassificationDDDDependencies } from "@aliaskeep/api-server/domains/classification";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aliaskeep/tests/shared";
import { CLASSIFICATION_USE_CASES } from "../__factories__/use-cases.js";

describe("GetQuarantineItem", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ClassificationDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ClassificationDDDDependencies>(
      CLASSIFICATION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetQuarantineItem, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { quarantineId: entity.id };

    await getQuarantineItem(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetQuarantineItem.execute).toHaveBeenCalledWith(expect.objectContaining({ quarantineId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { quarantineId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetQuarantineItem, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getQuarantineItem(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
