/**
 * Participant Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ParticipantEntity } from "@aliaskeep/core/participants/models/index.js";
import { participantsSchemas } from "@aliaskeep/core/participants";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prt";

export function createParticipant(overrides: Partial<ParticipantEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    consortiumId: overrides.consortiumId ?? `cns_${ulid().toLowerCase()}`,
    name: overrides.name ?? faker.person.fullName(),
    onboardingStatus: overrides.onboardingStatus ?? "pending",
    participantId: overrides.participantId ?? `prt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return participantsSchemas.Participant.parse(raw);
}

export function participantBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createParticipant(overrides));
}
