/**
 * RequireFabricIdentityPath handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fabric
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { requireFabricIdentityPath } from "@aliaskeep/api-server/domains/fabric/handlers";
import type { FabricDDDDependencies } from "@aliaskeep/api-server/domains/fabric";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aliaskeep/tests/shared";
import { FABRIC_USE_CASES } from "../__factories__/use-cases.js";

describe("RequireFabricIdentityPath", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FabricDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FabricDDDDependencies>(
      FABRIC_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRequireFabricIdentityPath, "execute").mockResolvedValue(useCaseResult);

    await requireFabricIdentityPath(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRequireFabricIdentityPath.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
