/**
 * ProfileRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fabric
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProfileRepository Port
 *
 * DDD: Application port for profilerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetFabricIdentityProfileInput, GetFabricIdentityProfileOutput, ListFabricIdentityProfilesInput, ListFabricIdentityProfilesOutput, SubmitFabricEnrollmentScanInput, SubmitFabricEnrollmentScanOutput } from "../dto/profile.dto";
export interface ProfileRepository {
  listFabricIdentityProfiles(input: ListFabricIdentityProfilesInput): Promise<ListFabricIdentityProfilesOutput>;
  submitFabricEnrollmentScan(input: SubmitFabricEnrollmentScanInput): Promise<SubmitFabricEnrollmentScanOutput>;
  getFabricIdentityProfile(input: GetFabricIdentityProfileInput): Promise<GetFabricIdentityProfileOutput>;
}

export type { GetFabricIdentityProfileInput, GetFabricIdentityProfileOutput, ListFabricIdentityProfilesInput, ListFabricIdentityProfilesOutput, SubmitFabricEnrollmentScanInput, SubmitFabricEnrollmentScanOutput } from "../dto/profile.dto";
